blank_issues_enabled: false
contact_links:
  - name: Support & Contact
    url: https://bim.atlstandards.com/resources/support/
    about: For urgent project questions, contact the ATL BIM Team directly via the support page.
